### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ruanbrand5** [OmgImAlexis/ee-docker#1]
Hi,

I trust you are well.

I'm currently experiencing an issue regarding setting up this container.

Please find attached a screenshot of this issue.

The src files that I am using is download from expression engine's website. Downloaded the ExpressionEngine Core file and extracted its contents to the src file of the docker container.

Could you please assist me?

Thank you,
![fileinfo](https://user-images.githubusercontent.com/28393301/31330187-95714c66-acdd-11e7-9571-29f6c16501c6.png)

**Comment by jamesrknights** [comment]
You'll need to install the FileInfo PHP extension.
